name: Deploy to Dockerhub

on:
  push:
    branches: [ master ]
    paths: 
      - Dockerfile
      - client/**
      - server/**
  repository_dispatch:
    types: [deploy]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    
    - name: Build & Publish Container
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: ${{ secrets.DOCKER_USERNAME }}/server-screens