name: Deploy to Dockerhub

on:
  push:
    branches: [ master ]
    paths: 
      - Dockerfile
      - client/**
      - server/**
  repository_dispatch:
    types: [deploy]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build --tag ${{ secrets.DOCKER_USERNAME }}/server-screens:latest .
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/server-screens